import type {Locale} from "@/types/database";
type Key="auth"|"profileApproval"|"fields"|"owner"|"dst"|"credits"|"conflict"|"save"|"created"|"updated"|"profileMissing"|"profileFields"|"profileSave"|"profileResubmit"|"profileUpdated"|"profileResubmitted";
const copy:Record<Locale,Record<Key,string>>={
  fr:{auth:"Connexion autorisée requise.",profileApproval:"Votre fiche praticien doit être validée avant de publier.",fields:"Vérifiez les champs indiqués. Votre saisie est conservée.",owner:"Choisissez le/la praticien·ne propriétaire.",dst:"Une répétition tombe sur une heure inexistante en Suisse. Choisissez une autre heure de départ.",credits:"Solde de publications épuisé. Aucun événement créé.",conflict:"Cette expérience a été modifiée entre-temps. Gardez votre brouillon et rechargez la page avant de réessayer.",save:"Enregistrement non confirmé. Votre saisie est conservée ; vous pouvez réessayer sans double débit.",created:"Expérience enregistrée.",updated:"Expérience mise à jour.",profileMissing:"Aucune fiche praticien trouvée.",profileFields:"Vérifiez les champs (les liens doivent être des URL complètes).",profileSave:"Mise à jour impossible.",profileResubmit:"Votre fiche est enregistrée, mais le renvoi en validation a échoué. Réessayez l’enregistrement.",profileUpdated:"Profil mis à jour.",profileResubmitted:"Profil mis à jour et renvoyé en validation."},
  de:{auth:"Eine Anmeldung ist erforderlich.",profileApproval:"Ihr Anbieterprofil muss vor der Veröffentlichung bestätigt werden.",fields:"Bitte prüfen Sie die markierten Felder. Ihre Eingaben bleiben erhalten.",owner:"Wählen Sie den/die verantwortliche·n Anbieter·in.",dst:"Ein wiederkehrender Termin fällt auf eine in der Schweiz nicht existierende Uhrzeit. Wählen Sie eine andere Startzeit.",credits:"Keine Publikations-Credits mehr verfügbar. Es wurde kein Erlebnis erstellt.",conflict:"Dieses Erlebnis wurde inzwischen geändert. Behalten Sie Ihren Entwurf und laden Sie die Seite neu.",save:"Speichern nicht bestätigt. Ihre Eingaben bleiben erhalten; Sie können ohne doppelte Belastung erneut versuchen.",created:"Erlebnis gespeichert.",updated:"Erlebnis aktualisiert.",profileMissing:"Kein Anbieterprofil gefunden.",profileFields:"Bitte prüfen Sie die Felder (Links müssen vollständige URLs sein).",profileSave:"Aktualisierung nicht möglich.",profileResubmit:"Ihr Profil wurde gespeichert, konnte aber nicht erneut eingereicht werden. Bitte versuchen Sie es erneut.",profileUpdated:"Profil aktualisiert.",profileResubmitted:"Profil aktualisiert und erneut zur Prüfung eingereicht."},
  en:{auth:"Authorised sign-in required.",profileApproval:"Your practitioner profile must be approved before publishing.",fields:"Please check the highlighted fields. Your input has been preserved.",owner:"Choose the practitioner who owns this experience.",dst:"A recurring date falls on a time that does not exist in Switzerland. Choose another start time.",credits:"Your publishing balance is empty. No experience was created.",conflict:"This experience was changed in the meantime. Keep your draft and reload the page before trying again.",save:"Save not confirmed. Your input has been preserved; you can retry without being charged twice.",created:"Experience saved.",updated:"Experience updated.",profileMissing:"No practitioner profile was found.",profileFields:"Please check the fields (links must be complete URLs).",profileSave:"Unable to update the profile.",profileResubmit:"Your profile was saved, but could not be resubmitted for review. Please try again.",profileUpdated:"Profile updated.",profileResubmitted:"Profile updated and resubmitted for review."}
};
export function actionLocale(formData:FormData):Locale{const value=String(formData.get("locale")??"en");return value==="fr"||value==="de"?value:"en"}
export function actionMessage(locale:Locale,key:Key){return copy[locale][key]}
