import type {Metadata} from "next";
import {getTranslations,setRequestLocale} from "next-intl/server";
import {Link} from "@/i18n/navigation";
import {createClient} from "@/lib/supabase/server";
import {CREDIT_PACKS,resolvePackPriceChf} from "@/lib/credits";
import {PackPrice} from "@/components/PackPrice";
import {Check,ArrowRight} from "lucide-react";

const SITE=process.env.NEXT_PUBLIC_SITE_URL??"https://forthesoul.ch";
export async function generateMetadata({params}:{params:Promise<{locale:string}>}):Promise<Metadata>{const {locale}=await params;const t=await getTranslations({locale,namespace:"becomePractitioner"});const path="/devenir-praticien";return {title:t("metaTitle"),description:t("metaDescription"),alternates:{canonical:`${SITE}${locale==="fr"?"":`/${locale}`}${path}`,languages:{fr:`${SITE}${path}`,de:`${SITE}/de${path}`,en:`${SITE}/en${path}`}}};}

export default async function BecomePractitionerPage({params}:{params:Promise<{locale:string}>}){const {locale}=await params;setRequestLocale(locale);const t=await getTranslations("becomePractitioner");const db=await createClient();const {data}=await db.from("settings").select("key,value");const settings=Object.fromEntries((data??[]).map(r=>[r.key,r.value]));const benefits=t.raw("benefits") as string[];const steps=t.raw("steps") as {title:string;text:string}[];const faq=t.raw("faq") as {q:string;a:string}[];const validityDays=Math.max(1,Number(settings.pack_default_valid_days)||365);
return <main>
  <section className="bg-gradient-to-br from-soul-sand to-soul-cream px-4 py-20 text-center"><p className="font-serif text-lg text-soul-brown">{t("eyebrow")}</p><h1 className="mx-auto mt-4 max-w-4xl text-4xl text-soul-brown sm:text-6xl">{t("title")}</h1><p className="mx-auto mt-5 max-w-2xl text-lg text-soul-bronze">{t("intro")}</p><Link href="/inscription" className="btn-primary mt-8">{t("cta")}<ArrowRight className="h-4 w-4"/></Link></section>
  <section className="mx-auto max-w-6xl px-4 py-16"><h2 className="text-3xl text-soul-brown">{t("benefitsTitle")}</h2><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{benefits.map(item=><div className="card flex gap-3 p-5" key={item}><Check className="h-5 w-5 shrink-0 text-soul-violet"/><p>{item}</p></div>)}</div></section>
  <section className="bg-white/60 py-16"><div className="mx-auto max-w-6xl px-4"><h2 className="text-3xl text-soul-brown">{t("stepsTitle")}</h2><div className="mt-8 grid gap-5 md:grid-cols-3">{steps.map(step=><article className="card p-6" key={step.title}><h3 className="text-xl text-soul-brown">{step.title}</h3><p className="mt-3 text-soul-ink/75">{step.text}</p></article>)}</div></div></section>
  <section className="mx-auto max-w-6xl px-4 py-16"><h2 className="text-3xl text-soul-brown">{t("packsTitle")}</h2><p className="mt-2 text-soul-bronze">{t("packsIntro")}</p><div className="mt-7 grid gap-5 sm:grid-cols-3">{CREDIT_PACKS.map(pack=><article className="card p-6" key={pack.id}><h3 className="text-xl">{t("packLabel",{count:pack.credits})}</h3><p className="mt-3 font-serif text-3xl"><PackPrice valueChf={resolvePackPriceChf(pack,settings)}/></p><p className="mt-2 text-sm text-soul-bronze">{t("packValidityDays",{count:validityDays})}</p></article>)}</div></section>
  <section className="mx-auto max-w-4xl px-4 py-16"><h2 className="text-3xl text-soul-brown">{t("faqTitle")}</h2><div className="mt-6 divide-y divide-soul-bronze/15 rounded-3xl bg-white px-6">{faq.map(item=><details className="py-5" key={item.q}><summary className="cursor-pointer font-semibold">{item.q}</summary><p className="mt-3 text-soul-ink/75">{item.a}</p></details>)}</div></section>
  <section className="mx-auto mb-16 max-w-5xl rounded-3xl bg-soul-violet px-6 py-12 text-center text-white"><h2 className="text-3xl text-white">{t("finalTitle")}</h2><p className="mx-auto mt-3 max-w-2xl text-white/85">{t("finalText")}</p><Link href="/inscription" className="mt-7 inline-flex rounded-full bg-white px-6 py-3 font-semibold text-soul-violet">{t("cta")}</Link></section>
</main>}
